///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesArrowBack = 'assets/images/Arrow_back.svg';
  static const String imagesBasket = 'assets/images/basket.png';

}
